### ISSUE TITLE
portfolio dashboard filter implementation

### ISSUE THREAD

**Issue by TrdHuy** [TrdHuy/TrdHuy.github.io#7]

**Comment by TrdHuy** [comment]
portfolio_dashboard.html
```html
<html style="height: max-content;">

<head>
     <link rel="stylesheet" href="./assets/css/base.css">
     <link rel="stylesheet" href="./assets/css/index.css">
     <link rel="stylesheet" href="./assets/css/portfolio_dashboard.css">
     <link rel="preconnect" href="https://fonts.googleapis.com">
     <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
     <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
</head>

<body style="background: var(--eerie-black-2); height: max-content;">

     <div id="portfolio-overview-area" class="portfolio-overview-area active">
          <ul id="category-filter-list" class="filter-list">

               <li id="category-filter-list-item" class="filter-item">
                    <button data-filter-btn>All</button>
               </li>
          </ul>

          <div class="filter-select-box">

               <button class="filter-select" data-select>

                    <div class="select-value" data-selecct-value>Select category</div>

                    <div class="select-icon">
                         <ion-icon name="chevron-down"></ion-icon>
                    </div>

               </button>

               <ul id="category-select-list" class="select-list">
                    <li id="category-select-list-item" class="select-item">
                         <button data-select-item>All</button>
                    </li>
               </ul>

          </div>

          <ul id="portfolio-list" class="project-list">
               <li id="portfolio-list-item" class="project-item" data-filter-item data-category="web development">
                    <figure class="project-img">
                         <div class="project-item-icon-box">
                              <ion-icon name="eye-outline"></ion-icon>
                         </div>
                         <img src="./assets/images/project-1.jpg" alt="finance" loading="lazy" portfolio-list-item-img>
                    </figure>

                    <h3 class="project-title" portfolio-list-item-title>Finance</h3>

                    <p class="project-category" portfolio-list-item-category>Web development</p>
               </li>
          </ul>
     </div>


     <div id="portfolio-page-detai" class="portfolio-page-detai">
          <div class="flex-horizontal-layout" style="align-items: center;">
               <button id="portfolio-close-btn" class="icon-btn">
                    <ion-icon name="chevron-back"></ion-icon>
               </button>
               <div>
                    <h3 id="portfolio-page-title" class="h3">Portfolio</h3>
                    <!-- <p class="underline-for-text"></p> -->
               </div>
          </div>

          <iframe id="portfolio-page-iframe-container" allowTransparency="true" scrolling="no" frameborder="0"
               allowfullscreen="true" style="width: 100%; height: auto; margin-top: 30px;"></iframe>
     </div>
</body>

<footer>
     <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
     <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
     <script src="./assets/js/contract.js"></script>
     <script src="./assets/js/common.dynamicSizeIframe.js"></script>
     <script src="./assets/js/portfolio_dashboard.js"></script>

</footer>

</html>
```

**Comment by TrdHuy** [comment]
portfolio_dashboard.css
```css
/*-----------------------------------*\
  #PORTFOLIO
\*-----------------------------------*/

.portfolio-overview-area {
    display: none;
}

.portfolio-overview-area.active {
    display: block;
    animation: scaleUp 0.25s ease forwards;
}

.filter-list {
    display: none;
}

.filter-select-box {
    position: relative;
    margin-bottom: 25px;
}

.filter-select {
    background: var(--eerie-black-2);
    color: var(--light-gray);
    display: flex;
    justify-content: space-between;
    align-items: center;
    width: 100%;
    padding: 12px 16px;
    border: 1px solid var(--jet);
    border-radius: 14px;
    font-size: var(--fs-6);
    font-weight: var(--fw-300);
}

.filter-select.active .select-icon {
    transform: rotate(0.5turn);
}

.select-list {
    background: var(--eerie-black-2);
    position: absolute;
    top: calc(100% + 6px);
    width: 100%;
    padding: 6px;
    border: 1px solid var(--jet);
    border-radius: 14px;
    z-index: 2;
    opacity: 0;
    visibility: hidden;
    pointer-events: none;
    transition: 0.15s ease-in-out;
}

.filter-select.active+.select-list {
    opacity: 1;
    visibility: visible;
    pointer-events: all;
}

.select-item button {
    background: var(--eerie-black-2);
    color: var(--light-gray);
    font-size: var(--fs-6);
    font-weight: var(--fw-300);
    text-transform: capitalize;
    width: 100%;
    padding: 8px 10px;
    border-radius: 8px;
}

.select-item button:hover {
    --eerie-black-2: hsl(240, 2%, 20%);
}

.project-list {
    display: grid;
    grid-template-columns: 1fr;
    row-gap: 20px;
    margin-bottom: 10px;
}

.project-item {
    display: none;
    animation: scaleDown 0.25s ease forwards;
}

.project-item.active {
    width: 100%;
    flex-direction: column;
    display: flex;
    animation: scaleUp 0.25s ease forwards;
}

@keyframes scaleUp {
    0% {
        transform: scale(0.5);
    }

    100% {
        transform: scale(1);
    }
}

@keyframes scaleDown {
    0% {
        transform: scale(1);
    }

    100% {
        transform: scale(0.0);
    }
}
.project-img {
    position: relative;
    width: 25vw;
    height: 20vw;
    border-radius: 16px;
    overflow: hidden;
    margin-bottom: 15px;
}

.project-img::before {
    content: "";
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: transparent;
    z-index: 1;
    transition: var(--transition-1);
}

.project-item:hover {
    cursor: pointer;
}

.project-item:hover .project-img::before {
    background: hsla(0, 0%, 0%, 0.5);
}

.project-item-icon-box {
    --scale: 0.8;

    background: var(--jet);
    color: var(--orange-yellow-crayola);
    position: absolute;
    top: 50%;
    left: 50%;
    transform: translate(-50%, -50%) scale(var(--scale));
    font-size: 20px;
    padding: 18px;
    border-radius: 12px;
    opacity: 0;
    z-index: 1;
    transition: var(--transition-1);
}

.project-item:hover .project-item-icon-box {
    --scale: 1;
    opacity: 1;
}

.project-item-icon-box ion-icon {
    --ionicon-stroke-width: 50px;
}

.project-img img {
    width: 100%;
    height: 100%;
    object-fit: cover;
    transition: var(--transition-1);
}

.project-item:hover img {
    transform: scale(1.1);
}

.project-title,
.project-category {
    margin-left: 10px;
}

.project-title {
    color: var(--white-2);
    font-size: var(--fs-5);
    font-weight: var(--fw-400);
    text-transform: capitalize;
    line-height: 1.3;
}

.project-category {
    color: var(--light-gray-70);
    font-size: var(--fs-6);
    font-weight: var(--fw-300);
}

.portfolio-page-detai {
    display: none;
}

.portfolio-page-detai.active {
    display: block;
    animation: scaleUp 0.25s ease forwards;
}


.icon-btn {
    background: var(--onyx);
    border-radius: 8px;
    width: 32px;
    height: 32px;
    display: flex;
    justify-content: center;
    align-items: center;
    color: var(--white-2);
    font-size: 18px;
    opacity: 0.7;
}

.icon-btn:hover {
    opacity: 1;
}

.icon-btn ion-icon {
    --ionicon-stroke-width: 50px;
}

.underline-for-text {
    content: "";
    width: 100%;
    height: 3px;
    background: var(--text-gradient-yellow);
    border-radius: 3px;
}

@media (min-width: 450px) {

    /**
      * #PORTFOLIO 
      */
    .project-list {
        grid-template-columns: repeat(2, 1fr);
    }

    .project-img {
        width: 40vw;
        height: 35vw;
    }
}


@media (min-width: 580px) {

    /**
      * #PORTFOLIO
      */
    /* .project-list {
        grid-template-columns: repeat(3, 1fr);
    } */
    .project-list {
        grid-template-columns: repeat(3, 1fr);
    }

    .project-img {
        border-radius: 16px;
        width: 25vw;
        height: 20vw;
    }
}


@media (min-width: 768px) {


    /**
      * PORTFOLIO
      */

    .article-title {
        padding-bottom: 20px;
    }

    .filter-select-box {
        display: none;
    }

    .filter-list {
        display: flex;
        justify-content: flex-start;
        align-items: center;
        gap: 25px;
        padding-left: 5px;
        margin-bottom: 30px;
    }

    .filter-item button {
        color: var(--light-gray);
        font-size: var(--fs-5);
        transition: var(--transition-1);
    }

    .filter-item button:hover {
        color: var(--light-gray-70);
    }

    .filter-item button.active {
        color: var(--orange-yellow-crayola);
    }

    /* portfolio grid */

}

@media (min-width: 1024px) {

    /**
    * PORTFOLIO
    */

    .project-list {
        grid-template-columns: repeat(4, 1fr);
    }

    .project-img {
        border-radius: 16px;
        width: 20vw;
        height: 18vw;
    }
}
```
